### ISSUE TITLE
winning combo not matched against the player moves

### ISSUE THREAD

**Issue by vszontagh** [vszontagh/vszontagh.github.io#1]
Hi, 

The file I'm referring to is in the new folder/ main.js
The problematic area is in the hasWinner function (line 136- 156) condition not seems working well.
- If there is only one statement in the condition: ""playerXMove.indexOf(winingCombo[i][j]) !== -1 ""
  this alerts every time the value match with the currently pushed one, which is always gonna be true.
- Or if I have all the 3 statements in the condition it randomly send the winning statement even if it's not a winning combination, or if it is it just not recognize it. 
  I believe it somehow the for loop is not looping through each arrays each element.

In addition to this console loging the playerXMove and playerOMove returns that they are not defined, but when I console.loged them in line 115 and 116 it returned the correct values and they were defined globally on line 56-57.

I hope the above description makes sense.
Please let me know if you have any question.

Thanks for your help in advance!

Viki

**Comment by Jingo88** [comment]
Hey hope that code i slacked helped. Sorry I didn't see this earlier. Let me know if you need anything else.
